--- #YAML:1.0
name                : Bucardo
version             : 5.6.0
abstract            : Postgres multi-master replication system
author:              
  - Greg Sabino Mullane <greg@turnstep.com>

license             : bsd
dynamic_config      : 1
distribution_type   : module

requires:
  DBD::Pg             : 2.0
  DBI                 : 1.51
  DBIx::Safe          : 1.2.4
  ExtUtils::MakeMaker : 6.32
  File::Spec          : 0
  IO::Handle          : 1.24
  List::Util          : 0
  MIME::Base64        : 0
  Net::SMTP           : 0
  Pod::Parser         : 0
  Pod::Usage          : 0
  Sys::Hostname       : 1.11
  Sys::Syslog         : 0.13
  Time::HiRes         : 0
build_requires:
  Test::Harness       : 2.03
  Test::More          : 0.61
  Module::Signature   : 0.50

provides:
  Bucardo:
    file            : Bucardo.pm
    version         : 5.6.0
  bucardo:
    file            : bucardo
    version         : 5.6.0

resources:
  homepage          : https://bucardo.org/index.html
  MailingList       : https://bucardo.org/list.html
  bugtracker        : https://github.com/bucardo/bucardo/issues
  repository        : https://bucardo.org/repo.html
  license           : https://bucardo.org/license.html
meta-spec:
  version           : 1.3
  url               : http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by        : emacs
